add_newline = false

format = "[$username@$hostname](fg:#eceff4 bg:#88c0d0)[](fg:#88c0d0 bg:#81a1c1)[$directory](fg:#eceff4 bg:#81a1c1)[](fg:#81a1c1) "

[username]
format = "$user"
show_always = true

[hostname]
format = "$hostname"
ssh_only = false

[directory]
format = "$path"
truncation_length = 0
truncate_to_repo = false
